CREATE TABLE SETTING(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    vat INTEGER NOT NULL,
    weightLimit INTEGER NOT NULL,
    owPenaltyPerKG INTEGER NOT NULL
);

CREATE TABLE ITEM(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
quantity INTEGER NOT NULL,
kgPerPiece INTEGER NOT NULL,
pricePerPiece INTEGER NOT NULL);